// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Transaction struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	UserID        int64     `json:"user_id"`
	Action        string    `json:"action"`
	Amount        int32     `json:"amount"`
	PhoneNumber   string    `json:"phone_number"`
	NetworkNode   string    `json:"network_node"`
	Narration     string    `json:"narration"`
	Status        bool      `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
}
