// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int64       `json:"id"`
	FullName    string      `json:"full_name"`
	Email       string      `json:"email"`
	Password    string      `json:"password"`
	AccessToken pgtype.Text `json:"access_token"`
	CreatedAt   time.Time   `json:"created_at"`
}
