// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, payd_username, full_name, email, password, payd_username_key, payd_password_key, access_token, created_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PaydUsername,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.PaydUsernameKey,
		&i.PaydPasswordKey,
		&i.AccessToken,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, payd_username, full_name, email, password, payd_username_key, payd_password_key, access_token, created_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PaydUsername,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.PaydUsernameKey,
		&i.PaydPasswordKey,
		&i.AccessToken,
		&i.CreatedAt,
	)
	return i, err
}

const registerUser = `-- name: RegisterUser :one
INSERT INTO users (
    full_name, payd_username, email, password, payd_username_key, payd_password_key
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, payd_username, full_name, email, password, payd_username_key, payd_password_key, access_token, created_at
`

type RegisterUserParams struct {
	FullName        string `json:"full_name"`
	PaydUsername    string `json:"payd_username"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	PaydUsernameKey string `json:"payd_username_key"`
	PaydPasswordKey string `json:"payd_password_key"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error) {
	row := q.db.QueryRow(ctx, registerUser,
		arg.FullName,
		arg.PaydUsername,
		arg.Email,
		arg.Password,
		arg.PaydUsernameKey,
		arg.PaydPasswordKey,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PaydUsername,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.PaydUsernameKey,
		&i.PaydPasswordKey,
		&i.AccessToken,
		&i.CreatedAt,
	)
	return i, err
}
